version: '3.9'

services:
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"

  test:
    build: .
    command: pytest --cov=prices
    volumes:
      - .:/app
    depends_on:
      - web
